.editorconfig, .eslintrc.json, .github/workflows/lint.yml, .github/workflows/test.yml, .gitignore, CODE_OF_CONDUCT.md, README.md, babel.config.json, jest.config.js, package-lock.json, package.json, tsconfig.json
This PR sets up the repository with our standard dev tooling.
This includes linting, testing, transpiling, type checking, and GitHub CI.}
Most of the content is pulled straight from [upload-service](https://github.com/PermanentOrg/upload-service).  Changes include:
1. Adding linting to our CI
2. Using Node 16
3. Some minor style fixes to settings files
4. Tests pass even if there are no tests written
Resolves #1
=> Project Setup

.env.example, package-lock.json, package.json, src/logger.ts
This PR  practically copies the logger written for our [upload service](https://github.com/PermanentOrg/upload-service/issues/4).
The only change is that I directly installed the [logform](https://www.npmjs.com/package/logform) package.
Closes #10
=> Configure logging

docs/collisions.md
- Added version 2 doc for collision handling strategy
- Lots of agreed changes left out intentionally, would committed as "Version 3" changes to this file for tracking purposes.
The [original V2 Google Docs document](https://docs.google.com/document/d/13zsy2amn0AeEE_cA1gkZ9vM77acY3f3nxEkA7Rvox_g/edit?usp=sharing) would/should evolve into the document for the user experience team, so diagrams and user experience questions not included here. Unless someone thinks they should?
=> Collision handling strategy

docs/symlinks.md
Note our non-support for symlinks
=> Document no support for symlinks

docs/collisions.md
- add notes for incoming paths with dedupe strings 
- add basic test plan
=> Update collisions algorithm: incoming paths with dedupe strings, basic test plan

package-lock.json, package.json
This PR updates nodemon in order to address a vulnerability in one of nodemon's dependencies
=> Fix Got vulnerability

.env.example, .eslintrc.json, package-lock.json, package.json, src/classes/SftpSessionHandler.ts, src/classes/SshConnectionHandler.ts, src/classes/SshSessionHandler.ts, src/index.ts, src/server.ts, src/utils/generateDefaultAttributes.ts, src/utils/generateFileEntry.ts, src/utils/getLongname.ts, src/utils/index.ts, src/utils/loadPath.ts, src/utils/lookupFileType.ts
This PR adds support for loading archives from permanent and translating them to proper SFTP responses.
It does NOT support real authentication yet, and instead uses a temporary bearer token environment variable to handle the authentication use case.
=> Support loading archives from Permanent

.env.example, package-lock.json, package.json, src/classes/AuthenticationSession.ts, src/classes/PermanentFileSystem.ts, src/classes/SftpSessionHandler.ts, src/classes/SshConnectionHandler.ts, src/fusionAuth.ts
This PR adds support for authentication to the sftp service (before we were using a "hard coded" authentication so a given service would only work against a single local user).
This PR also fixes some bugs that I found when utilizing the OpenSSH cli client, though I may sneak them out of this PR and merge them seperately.
Resolves #15
=> Support authentication

README.md
This commit adds instructions on how to run `rclone` against the various Permanent instances.
=> How to run rclone

src/classes/PermanentFileSystem.ts, src/utils/getArchiveIdFromPath.ts, src/utils/index.ts
This PR fixes a bug in the archive ID regular expression.  It also puts the function in its own file, which will make it easier to write unit tests for in future.
Resolves #61
=> Fix archiveId parsing

src/classes/PermanentFileSystem.ts
This PR adds steps to populate the files of `Record` objects before generating file entries when opening a folder. This in turn means that files will be reported when listing directory contents over SFTP.
Resolves #65
=> Fix record lookup

README.md
In the "Troubleshooting rclone" section, add some information about how to include empty directories in 'rclone copy', link to the rclone option documentation online, and edit the existing item about MFA.
=> Add more info about using rclone with Permanent

README.md
This takes @Fenn-CS's suggestion from his review of PR #71.
=> Don't wrongly imply strict flag positioning

src/classes/SftpSessionHandler.ts, src/server.ts
This PR standardizes log levels to make it easier for us to control log levels appropriately in various environments.
as a reminder the log levels are:
```
error
warn
info
verbose
debug
silly
```
Resolves #70
=> Standardize log levels

src/classes/PermanentFileSystem.ts, src/classes/SftpSessionHandler.ts
This PR adds support for folder creation by implementing the `MKDIR` sftp command handlers.
Resolves #26
=> Implement `MKDIR`

src/classes/SftpSessionHandler.ts
This PR checks the AWS response code and only returns data if the response code indicates success.
Resolves #88 
Resolves #82
=> Detect and handle AWS status codes

src/classes/PermanentFileSystem.ts
This PR adds some logic to double-check if a file or folder is considered "missing" the first time we look for it.  With this addition we actually are able to simplify our cache management a bit (we no longer need to explicitly wipe out the cache data when creating new items, for instance).
Resolves #116
=> Bypass cache on miss

src/classes/SftpSessionHandler.ts
This PR replaces the `sync` version of filesystem calls with their async alternatives.
Resolves #113
=> Remove blocking filesystem calls

.eslintrc.json, package-lock.json, package.json, src/classes/PermanentFileSystem.ts, src/errors/FileStillProcessingError.ts, src/errors/InvalidOperationForPathError.ts, src/errors/NotFoundError.ts, src/errors/OperationNotAllowedError.ts, src/errors/ResourceDoesNotExistError.ts, src/errors/index.ts
This PR adds more specific error types to the PermanentFileSystem.
Please be sure to flag any error names that aren't intuitive to you or that you think would be better as something else.
Resolves #125
=> Throw more specific errors

docs/scaling.md
This PR provides some initial documentation about scalability concerns.
=> Document scaling thoughts

.eslintrc.json, src/classes/SshConnectionHandler.ts, src/classes/SshSessionHandler.ts
This PR updates our lint settings to current best practices according to eslint-config-airbnb-base/rules/best-practices
Resolves #227
=> Update lint settings

src/classes/SftpSessionHandler.ts, src/classes/TemporaryFileManager.ts, src/errors/MissingTemporaryFileError.ts, src/errors/index.ts
This PR refactors the way that temporary files are generated and accessed by the SFTP session handler, and incorporates functionality to "time out" temporary files that have not been accessed for a long period of time.
The PR also improves the way opened server resources are tracked.
Resolves #144
=> Refactor temporary storage management

README.md
- Fix bug in discussion of archive numbers (thanks to @liam-lloyd)
- Add more detail to 'rclone config' walk-through
- Give more background about '--inplace' flag to rclone
- Explain process of copying a local folder to Permanent
- Explain why 'rclone mkdir' is not officially supported
=> Update and improve rclone usage documentation

src/classes/PermanentFileSystem.ts
This PR improves `getItemType` so that it verifies the existence of archives before indicating it is a directory.  It now throws an appropriate error if the resource doesn't exist.
=> Verify existence of archive resources

src/classes/PermanentFileSystem.ts
This PR improves (and fixes) the path checks that are made at the beginning of the file creation and file deletion operations.
=> Correct creation / deletion path checks

src/classes/PermanentFileSystem.ts
This PR adds a more comprehensive and defensive check to verify that paths are valid before attempting to determine what type of Permanent entity the path is referencing.
This will help prevent edge cases where a user may have written specific types of invalid path in their rclone command.
Resolves #615
=> Add a universal path check

src/classes/SftpSessionHandler.ts
This PR updates the `SSH_FXP_MKDIR` handler to return `NOT_FOUND` and `PERMISSION` status codes when appropriate.
Resolves #628
=> Return specific status codes for `SSH_FXP_MKDIR`

src/classes/PermanentFileSystem.ts
This PR goes through each use of an `sdk` function and makes sure we are properly handling certain types of HTTP responses (404 and 402) in contexts where those statuses should be converted to a `PermanentFileSystem` error.
Resolves #612
=> Capture SDK errors in `PermanentFileSystem`
