PermanentOrg/sftp-service

- .gitignore
- README.md
- package-lock.json
- package.json
This PR adds a `npm run dev` and also updates`npm start` to run off of transpiled code instead of through `babel-node`
To test this you need to run `npm install`
It also updates the build destination to be `/build` instead of `/lib` since that feels more explicit.
Resolves #5
> Update start commands

- .env.example
- README.md
- package-lock.json
- package.json
- src/index.ts
This PR makes it possible to configure an environment to report to Sentry
Testing this involves `npm install`
Resolves #4 
(This builds on top of #6, so please don't review until that is merged and this is rebased)
> Add Sentry

- .env.example
- package-lock.json
- package.json
- src/classes/SshConnectionHandler.ts
- src/index.ts
- src/server.ts
This PR sets up the skeleton of the SSH2 server aspect of our SFTP server.
These event handlers don't actually perform any logic, but they create spaces to cover all of the connection events defined in the [ssh2 package documentation](https://www.npmjs.com/package/ssh2#connection-events)
You can test if this is working by updating your `.env` with the new values, and then running:
```
ssh 127.0.0.1 -p22222
```
You should then see:
```
Unable to negotiate with 127.0.0.1 port 22222: no matching host key type found. Their offer:
```
^ Note that I am using `SSH_PORT=222222` and if you use a different value you'd need to adjust the test accordingly.
Issue #3
> Add stubbed SSH event handlers

- .env.example
- .gitignore
- README.md
- src/server.ts
This PR adds documentation for creating / configuring the server with a host key, and adds logic for using that host key when starting the SSH2 server.
To test this you should:
1. Follow the new README instructions for generating a host key.
2. Populate the `.env` with a path to your new host key
3. Start the server.
Once you do that you should be able to run `ssh 127.0.0.1 -p22222` and see no warnings / etc.  It will sit there doing nothing:
When you stop the server you should see a "Connection closed" message on your SSH client (though this is probably client specific)
> Support host keys

- src/classes/SshConnectionHandler.ts
- src/server.ts
This PR adds a handler for the `authentication` event, though the handler isn't very smart yet.  It tells the client to use a password and then accepts whatever password the client provides.
While I'd like to say this is a philosophical decision and social commentary on the dehumanizing impact of nations and borders, the reality is I want to confirm that the permanent SDK is ready for action before incorporating it into the authentication flow.
You'll know this is working if you get a password prompt after running
```
ssh 127.0.0.1 -p22222
```
You should also see the following output on the service console:
> Support "authentication"

- src/classes/SftpStreamHandler.ts
- src/classes/SshConnectionHandler.ts
- src/classes/SshSessionHandler.ts
- src/server.ts
This PR adds the stubbed out skeleton for the set of sftp events that we'll need to implement in order to support the sftp protocol.  This won't actually do anything yet and so I don't believe an SFTP client would have a good time trying to invoke anything, however you should see activity if you try:
> Stub out SFTP session handler

- package-lock.json
- package.json
- src/classes/PermanentFileSystem.ts
- src/utils/generateFileEntriesForFolders.ts
- src/utils/generateFileEntriesForRecords.ts
This PR updates the SFTP service to use the latest Permanent SDK, and in particular stops using the Folder "name" property (which does not guarantee filesystem safety), instead using `fileSystemCompatibleName`.
It also updates `fileName` on Records to the new attribute name.
Resolves #60
> Use fileSystemCompatibleName for items

- README.md
The `rclone config` prompts mention "SSH" in a possibly-confusing way when asking for username.  Therefore, I've moved the part of our instructions that clarifies why rclone is mentioning "SSH" at all to a bit earlier, to line up with that mention.  (It could also go where the "host>" is prompted, right before the username prompt, but I think confusion is most likely to happen with username because people have a pre-existing idea of what their SSH username is.)
This will help users who have experience with SSH better understand what's going on.
> In usage instructions, clarify SSH's role earlier

- src/classes/PermanentFileSystem.ts
- src/classes/SftpSessionHandler.ts
- src/utils/generateAttributesForFolder.ts
- src/utils/index.ts
This PR updates the various FSTAT handlers to actually leverage Permanent data when generating a response.
Note that this branch is based off of code included in #66, and so this PR shouldn't be reviewed until after that PR is merged and this gets rebased again.
Resolves #64
> Generate correct file attributes

- src/classes/PermanentFileSystem.ts
- src/utils/deduplicateFileEntries.ts
- src/utils/index.ts
This PR de-duplicates file entries generated from the Permanent API response when loading a folder.
Resolves #56
> Ensure unique file entries

- src/classes/SshConnectionHandler.ts
- src/classes/SshSessionHandler.ts
This PR adds some fairly gnarly code to accommodate a bug in the upstream library that handles implementation of the ssh / sftp protocol's more inner workings.
There is [already an upstream patch](https://github.com/mscdex/ssh2/pull/1111) which unfortunately has not been merged yet.  Once that is merged we can delete this local patch.
Resolves #45
> Fix rclone hang

- package-lock.json
- package.json
- src/classes/PermanentFileSystem.ts
- src/classes/SftpSessionHandler.ts
This PR adds functionality for writing files to Permanent.
It has a few known limitations (which have been captured in issues already):
1. It does not support empty file uploads (see #79)
2. It does not support `mod time` (see #80)
3. It does not support changes to existing files in permanent (see https://github.com/PermanentOrg/sftp-service/issues/81)
Resolves #48 
Resolves #24
> Implement file upload

- src/classes/AuthenticationSession.ts
- src/classes/PermanentFileSystemManager.ts
- src/classes/SftpSessionHandler.ts
- src/classes/SshConnectionHandler.ts
- src/classes/SshSessionHandler.ts
- src/classes/index.ts
- src/server.ts
This PR creates a "manager" layer that will provide the same filesystem for any connection that has been established on behalf of a given user.  It will also ensure that those filesystems are deleted after 5 minutes of inactivity.
Resolves #76
> Share filesystems per user

- src/classes/SftpSessionHandler.ts
- src/classes/SshConnectionHandler.ts
- src/classes/SshSessionHandler.ts
- src/server.ts
This PR updates some of our class functions so they are more consistent in NOT using arrow functions.
The functionality should all be the same, though this does impact some inner workings of how the functions themselves are created and called.
Resolves #85
> Remove arrow functions for class methods

- package-lock.json
- package.json
This PR updates the SDK to 0.5.1 which resolves an issue where certain archive root folders were resulting in SDK errors.
I don't think we had an open issue for this here, but it was causing failures in download in certain legacy cases.
> Update permanent sdk to v0.5.1

- README.md
Document the need for modtime flags (issue #84), how to download just a single specific archive, and how to upload to a specific archive.
> Expand documentation of rclone usage

- README.md
This PR tweaks documentation to specify the use of the `--size-only` flag when downloading.
Issue #84
> Add size flag to download

- package-lock.json
- package.json
- src/classes/PermanentFileSystem.ts
- src/utils/getArchiveIdFromPath.ts
- src/utils/getArchiveSlugFromPath.ts
- src/utils/index.ts
This PR changes the value used in archive folder paths from the archive's ID to the archive's slug
Resolves #91
> Use slug instead of archive ID

- src/classes/PermanentFileSystem.ts
- src/utils/generateAttributesForArchive.ts
- src/utils/generateAttributesForFile.ts
- src/utils/generateAttributesForFolder.ts
- src/utils/index.ts
This PR fixes a few bugs related to the reported mtimes for files and folders.  In particular it now properly uses seconds (instead of ms) when reporting the dates.  It also uses the archive data for archive folders.
It does not address the `/archives` folder, which does not actually exist in permanent and should likely be linked to the user's account creation date, but I'd like to address that as part of #100 
Note this can be tested locally using the `rclone lsjson` command which will show the mtimes associated with various items in a path.
Resolves #98
> Fix mtime dates

- src/classes/PermanentFileSystem.ts
- src/classes/SftpSessionHandler.ts
This PR adds some limits to when the cache is used in an attempt to avoid cases when new content isn't available in the cache.  It maintains the use of caching for:
1. directory navigation (e.g. loading a file won't cause one API call per directory depth if the paths had already been loaded before).
2. directory content listing (e.g. running `ls` won't cause one API call per record if the records already existed).
Related to #102
> Add cache bypasses

- src/classes/SftpSessionHandler.ts
This PR is a temporary patch to prevent hangs in the event that rclone has a reason to attempt to request the removal of a file or folder.  The remove will fail, but before we weren't even sending a response which would result in hangs from the sftp client's perspective.
Related to #25
> Return failure status on remove operations

- src/classes/SftpSessionHandler.ts
This PR removes a nasty bug that was coming from double-closing of the same file ID (the `tmp` library closes files as part of cleanup, so we don't need to close it directly).
Issue #111
Issue #99
> Prevent double closing

- package-lock.json
- package.json
- src/classes/PermanentFileSystem.ts
- src/classes/SftpSessionHandler.ts
This PR adds support for the RMDIR handler -- meaning a user could delete directories from permanent via SFTP.
NOTE: Until the permanent SDK actually populates this setting from real API responses the setting will always be "false" / this code won't actually run.
> Implement support for sftp RMDIR

- src/classes/SftpSessionHandler.ts
This PR fixes a few SFTP handlers that were not providing a response to the SFTP client, which could result in client hangs in some circumstances.
Resolves #121
> Ensure sftp calls always resolve

- .github/dependabot.yml
This PR does not allow dependabot to try to upgrade our `node-fetch` version to 3.x.
> Override node-fetch dependabot settings

- .env.example
Copying and pasting the existing local remote from `.env.example` (`http://local.permanent.org/api`) could lead to some unwarranted debugging.
> Correct local remote addresse in .env.example

- src/classes/SftpSessionHandler.ts
This PR updates our `catch` clauses to log any caught erros in debug.
Note that in some cases the "error" is expected to be caught and is part of intended control flows (though as I type this I realize that might be an anti pattern...).
Regardless, these logs should help us going forward.
> Log caught errors

- src/classes/SftpSessionHandler.ts
This PR adds messages to failure (and permission denied) status responses, which are intended to provide additional user context when something goes wrong.
Resolves #52
> Add messages to failure statuses

- README.md
In new versions of rclone it will try to upload to ".partial" files by default and rename them to the proper destination filename after uploading is fully completed. Unfortunately, we have not implemented the rename command in SFTP yet, so this current upload flow doesn't work with the sftp-service. Add instructions to the README to show users which flag to pass into rclone to get it to work.
> Add `--inplace` flag instructions to README

- src/classes/PermanentFileSystem.ts
This PR improves our caching logic so that we update our local caches to reflect the state of permanent upon archive record and archive folder creation.  In both cases this will prevent unnecessary call to the permanent back end.
I did verify locally that this lowers the number of calls to the API by 1 for each archive record being created.
Resolves #306
> Update caches on item creation

- src/classes/PermanentFileSystem.ts
This PR fixes an issue with the recently improved cache updating logic so that folders are updated with information about newly created items regardless of whether they are "root level" archive folders.  The original fix would only update caches for folders that had been created within the root level archive folders.
Resolves #306
> Properly update archiveFolder cache

- src/classes/PermanentFileSystem.ts
This PR continues to improve our cache updating logic to avoid preventable API calls.
Resolves #306
> Create cache entries for new items

- src/classes/PermanentFileSystem.ts
This PR reverts part of a change made in https://github.com/PermanentOrg/sftp-service/commit/9fff82d39c6074164613ffbe8c799386e6607614.  I *believe* we no longer need this logic now that we have caches that get updated on file creation.  Note that this DOES mean if a file is created via a completely separate client at the same time as an SFTP upload it could result in confusing behavior / duplication (though one could argue if you upload the same file twice from two clients, it would be expected to appear twice).
Resolves #316
> Avoid unnecessary cache bypass

- src/classes/PermanentFileSystem.ts
- src/classes/SftpSessionHandler.ts
This PR updates our cache buster so that it is generally NOT invoked when files are being opened for the purposes of writing.
It does make sure that at least the parent folder has been loaded into the cache (though this would only need to happen once per folder, which seems appropriate)
Resolves #308
> Bypass cache busting when opening files for write

- src/classes/PermanentFileSystem.ts
- src/errors/FileStillProcessingError.ts
- src/errors/index.ts
Now that the back end populates FileVOs in the response of `registerRecord` (see: https://github.com/PermanentOrg/back-end/pull/525), we don't have to wait an arbitrary amount of time for processing to happen on files. Remove the code that performs this wait, since its no longer necessary and it adds a theoretical 1 second delay per file in the upload process.
> Remove wait for FileVOs to be populated

- src/classes/SftpSessionHandler.ts
This PR fixes a very strange and inefficient (I wrote it so I can say this) approach to verifying that a file path is, in fact, a file path as opposed to a directory path.
The new logic is more direct and will also benefit from caching.
Resolves #577
> Use `getItemType` to validate path type

- src/classes/PermanentFileSystem.ts
- src/classes/SftpSessionHandler.ts
This PR removes some very expensive and fragile calls to the permanent API, which are no longer necessary thanks to the recent SDK upgrades which use Stela to populate folders with their children.
It also adds support for pagination in the SFTP response when loading folders, which should result in more scalable interactions with folders with lots of children.
> Dramatically improve upload performance

- src/classes/SftpSessionHandler.ts
This PR updates our SftpSessionHandler to only return `NO_SUCH_FILE` to an sftp client if the PermanentFileSystem explicitly throws a `ResourceDoesNotExistError`.
Prior to this PR the SFTP service would incorrectly report that files and folders didn't exist if there were network or API errors when attempting to retrieve them.
This change at least gives SFTP clients a chance to potentially handle a thrown error more gracefully.
Another byproduct of this change is that we will no longer log "errors" when files don't exist (a file not existing is expected behavior).
Resolves #590
> Only return `NO_SUCH_FILE` if a resource truly wasn't found

- package-lock.json
- package.json
- src/classes/PermanentFileSystem.ts
This PR upgrades to the latest permanent SDK and enables the retryOn functionality for a few 5xx errors.
This won't prevent 504 responses but it may help resolve some of them without resorting to a FAILURE response to the SFTP client.
Resolves #592
> Retry on various 5xx errors

- src/classes/PermanentFileSystem.ts
- src/errors/NotFoundError.ts
- src/errors/index.ts
This PR removes a duplicated error type (which was mistakenly not being handled properly when I added support for `Failure` vs `NotFound` SFTP status codes earlier this year)
Using only the handled error also resolves an issue where folder creation was failing due to that incorrect status code.
Resolves #607
> Remove duplicate error type

- src/classes/PermanentFileSystem.ts
- src/classes/SftpSessionHandler.ts
- src/errors/FileSystemObjectNotFound.ts
- src/errors/ResourceDoesNotExistError.ts
- src/errors/index.ts
This PR improves our function and variable names to be more specific when we are referring to filesystem paths and filesystem objects.
This can seem verbose, but the clarity it provides is important because the permanent filesystem is bridging the gap between the API and a virtual filesystem.
> Normalize filesystem language

- src/classes/PermanentFileSystem.ts
- src/errors/InvalidOperationForPathError.ts
- src/errors/OperationNotAllowedError.ts
- src/errors/PermissionDeniedError.ts
- src/errors/index.ts
This PR fixes two issues:
1. It renames a confusingly named error (`OperationNotAllowedError`) and replaces it with a more explicitly permission-related error.
2. It fixes a mistaken use of `InvalidOperationForPathError` and clarifies what `InvalidOperationForPathError` is for
> Improve permission error name

- .github/dependabot.yml
This PR adds a dependabot group for `@babel` dependencies so that we can review the related upgrades together.
> Group @babel dependabot updates

- src/classes/SftpSessionHandler.ts
This PR improves our `OPENDIR` handler to return `NO_SUCH_FILE` in the event that the requested directory (or directory path) doesn't exist.
Resolves #625
> Return `NO_SUCH_FILE` for `SSH_FXP_OPENDIR`

- src/classes/SftpSessionHandler.ts
This PR improves our status code granularity for the case when a directory path doesn't exist for a given file open-for-write operation.
Resolves #627
> Reply with `NO_SUCH_FILE` for writable-file-open operations

- src/classes/SftpSessionHandler.ts
This PR adds more consistent use of `PERMISSION_DENIED` in our SFTP operation handlers.
It also includes a couple of additional instances where `FILE_NOT_FOUND` was being returned incorrectly; I included those in a separate commit (but this PR, since it was all part of the same "updated error processing" block)
Resolves #631
> Consistently return `PERMISSION_DENIED` correctly

- src/classes/SftpSessionHandler.ts
This PR returns the more specific `SSH_FX_OP_UNSUPPORTED` failure status when an un-implemented SFTP operation is called.
Resolves #634
> Return `OP_UNSUPPORTED` for unsupported operations

- src/classes/PermanentFileSystem.ts
This PR catches a bespoke error thrown by the SDK when a folder doesn't exist.
Related to https://github.com/PermanentOrg/permanent-sdk/issues/518
Resolves #646
> Handle bespoke sdk error for folder lookup

- package-lock.json
- package.json
- src/classes/PermanentFileSystem.ts
This PR extends the duration that we retry on certain API call failures.  This is particularly important if we're getting rate limit errors.
Resolves #650
> Retry for longer
